config/routes.rb
FileUpload::Application.routes.draw do
  resources :uploads
  root 'uploads#index'
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_attached_file :uploaded_file, styles: { original: "4000x4000>", large: "1500x1500>", medium: "300x300>", small: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :uploaded_file, 
  content_type: [
  "image/jpg", 
  "image/jpeg", 
  "image/png", 
  "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all.order("created_at DESC")
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.create(upload_params)
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params[:upload].permit(:uploaded_file, :name, :price, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileUpload</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <!-- Inclue Twitter bootstrap -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <p class="navbar-text navbar-left">
          <%= link_to "Items", root_path, class: "btn btn-default"  %>
        </p>
        <p class="navbar-text navbar-left">
          <%= link_to 'New Item', new_upload_path, class: "btn btn-default"  %>
        </p>
      </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/uploads/_form.html.erb
<%= form_for(@upload, html: { multipart: true }) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
        <% @upload.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.label :uploaded_file, t('.upload_new_file') %>
    <%= f.file_field :uploaded_file, multiple: true, name: 'upload[uploaded_file]' %>
    <%= f.submit %>
  </div>
<% end %>

<% # jquery upload template # %>
<script id="template-upload" type="text/x-tmpl">
  <div class="upload">{%=o.name%}<div class="progress"><div class="progress-bar bar" style="width: 0%"></div></div></div>
</script>

app/views/uploads/_upload.html.erb
<p>
  <strong>Title:</strong>
  <%= @upload.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @upload.description %>
</p>
<p>
  <strong>Price:</strong>
  <%= @upload.price %>
</p>

<% if @upload.uploaded_file.exists? %>
  <%= image_tag(@upload.uploaded_file(:small), class: 'thumb')  %>
<% end %>

app/views/uploads/create.js.erb
<% if @upload.new_record? %>
  alert('Failed');
<% else %>
  if ($('h1') !== undefined) {
    $('h1').append("<%=j render partial: 'uploads/upload', locals: { upload: @upload } %>");
  }
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload, class: "btn btn-default" %>
<%= link_to 'Back', uploads_path, class: "btn btn-default" %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<% @uploads.each do |upload| %>
  <div class="row" id="recipe_top">
    <div class="col-md-8">
      <h2><%= link_to upload.name, upload %></h2>
      <p>
        <% if upload.uploaded_file.exists? %>
          <%= image_tag upload.uploaded_file.url(:medium) %><br/>
        <% end %>
      </p>
      <p><%= "#{time_ago_in_words(upload.created_at)} ago" %></p>
      <p><%= upload.price %></p>
      <p><%= upload.description %></p>
      <br>
      <%= link_to 'Show', upload, class: "btn btn-default"  %>
      <%= link_to 'Edit', edit_upload_path(upload), class: "btn btn-default"  %>
      <%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"  %>
    </div>
  </div>
<% end %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path, class: "btn btn-default" %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<br />
<%= render 'upload' %>
<br />
<br>
<%= link_to 'Edit', edit_upload_path(@upload), class: "btn btn-default" %>
<%= link_to 'Back', uploads_path, class: "btn btn-default" %>